namespaces:
  default: "interopspec"

datasets:
  small_sales_events:
    rows: 1000
    columns:
      - { name: event_id, type: bigint }
      - { name: tenant_id, type: int }
      - { name: event_ts, type: timestamp }
      - { name: sku, type: string }
      - { name: qty, type: int }
      - { name: price, type: decimal(18,2) }
      - { name: country, type: string }
      - { name: ds, type: date }
    partition_spec:
      - { transform: days, column: event_ts }
      - { transform: bucket, num_buckets: 16, column: tenant_id }
    sort_order:
      - event_ts
      - tenant_id
    table_properties:
      write.distribution-mode: hash
      commit.manifest.min-count-to-merge: 100
      format-version: 2

plans:
  spark_create_load:
    steps:
      - engine: spark
        action: create_table
        dataset: small_sales_events
      - engine: spark
        action: bulk_insert
        dataset: small_sales_events
  interop_small:
    steps:
      - engine: spark
        action: create_table
        dataset: small_sales_events
      - engine: spark
        action: bulk_insert
        dataset: small_sales_events
      - engine: databricks
        action: add_column_and_append
        args:
          new_column: { name: channel, type: string, default: "web" }
      - engine: snowflake
        action: merge_updates_and_deletes
        args:
          updates: 1000000
          deletes: 250000
      - engine: spark
        action: time_travel_validate
  clean:
    steps:
      - engine: spark
        action: clean
        dataset: small_sales_events
  read:
    steps:
      - engine: databricks
        action: read_validate
        dataset: small_sales_events
      - engine: snowflake
        action: read_validate
        dataset: small_sales_events
  snowflake_branching:
    steps:
      - engine: spark
        action: create_table
        dataset: small_sales_events
      - engine: spark
        action: bulk_insert
        dataset: small_sales_events
      - engine: snowflake
        action: create_branch
        args:
          branch_name: feature_branch
      - engine: snowflake
        action: read_validate
        dataset: small_sales_events
        args:
          branch_name: feature_branch
      - engine: snowflake
        action: merge_branch
        args:
          source_branch: feature_branch
          target_branch: main
