# Engine and catalog configuration
# Fill in environment variables or inline secrets for testing only.

storage:
  warehouse_uri: "abfss://iceberg-warehouse@${ADLS_ACCOUNT}.dfs.core.windows.net/"
  account: "${ADLS_ACCOUNT}"
  container: "iceberg-warehouse"

spark:
  enabled: true
  version: "3.5"
  iceberg_runtime_version: "1.4.3"
  catalog:
    name: "internal"
    impl: "org.apache.iceberg.rest.RESTCatalog"
    uri: "${CATALOG_URI}"
  conf:
    spark.master: "local[*]"
    spark.driver.extraJavaOptions: "-Djava.security.manager=allow"
    spark.executor.extraJavaOptions: "-Djava.security.manager=allow"
    spark.jars.repositories: "https://repo1.maven.org/maven2,https://repo.maven.apache.org/maven2,https://maven-central.storage-download.googleapis.com/maven2"
    spark.jars.packages: "org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.1,org.apache.iceberg:iceberg-azure-bundle:1.4.1"
    spark.sql.extensions: "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
    spark.sql.defaultCatalog: "interop"
    spark.sql.catalog.interop: "org.apache.iceberg.spark.SparkCatalog"
    spark.sql.catalog.interop.type: "rest"
    spark.sql.catalog.interop.uri: "${CATALOG_URI}"
    spark.sql.catalog.interop.header.X-Iceberg-Access-Delegation: "vended-credentials"
    spark.sql.catalog.interop.credential: "${PRINCIPAL}"
    spark.sql.catalog.interop.warehouse: "internal"
    spark.sql.catalog.interop.scope: "PRINCIPAL_ROLE:spark"

# Databricks (not used for local Spark run)
databricks:
  enabled: true
  host: "${DATABRICKS_HOST}"
  token: "${DATABRICKS_TOKEN}"
  uc:
    catalog: "interop_uc"
    storage_credential: "spn_iceberg"
    external_location: "abfss://iceberg-warehouse@${ADLS_ACCOUNT}.dfs.core.windows.net/"

snowflake:
  enabled: true
  account: "${SNOWFLAKE_ACCOUNT}"
  user: "${SNOWFLAKE_USER}"
  password: "${SNOWFLAKE_PASSWORD}"
  role: "${SNOWFLAKE_ROLE}"
  warehouse: "${SNOWFLAKE_WAREHOUSE}"
  database: "${SNOWFLAKE_DATABASE}"
  polaris:
    enabled: true
    # Placeholder for Polaris catalog endpoint/registration details
    catalog_name: "open_snowflake"
